### ISSUE TITLE
Recommendation: Turn on this mode by default for all web pages

### ISSUE THREAD

**Issue by ghzxs** [Owyn/Universal_Dark_Theme#3]
Each web page needs to be opened manually, which is a very tedious operation. If the web page does not need to run this script, it must be closed manually. This script is very good. I hope the author can optimize it as soon as possible. Thank you.

**Comment by Owyn** [comment]
Turning it on by default for every website won't produce good results, that is why it is not like that.

**Comment by ghzxs** [comment]
But when I run it on iPhone safari, there are no shortcut keys and the operation is very complicated.

**Comment by ghzxs** [comment]
Is it complicated to modify this code to enable it by default? Can you please give me some guidance to modify it for my own use?

**Comment by Owyn** [comment]
> But when I run it on iPhone safari, there are no shortcut keys and the operation is very complicated.

Perhaps you could use a different userscript manager for safari which has hotkeys?

If you want to reverse ON\OFF behavior you'd have to switch line 41 & 44
![image](https://github.com/Owyn/Universal_Dark_Theme/assets/1309656/85ebe50b-6d8d-46b0-aa2d-c1cfe1977eb0)
