### ISSUE TITLE
Help selecting CCS element

### ISSUE THREAD

**Issue by scottsteely** [Owyn/Universal_Dark_Theme#4]
Hey, I've really been enjoying your Tamper Monkey script. I was wondering if you could help me select the text color to change on upstract.com.

![Screenshot_23-Apr_19-34-07_8954](https://github.com/Owyn/Universal_Dark_Theme/assets/59208640/cf7c4e40-893c-4fc9-ad53-f7919ae53ad7)

**Comment by Owyn** [comment]
![image](https://github.com/Owyn/Universal_Dark_Theme/assets/1309656/5237083a-df48-4ad9-940e-1cbc1c6407dd)

then put it into the "custom CSS style" setting while changing the color to the one you want

**Comment by scottsteely** [comment]
Worked like a charm. Thanks!
