### ISSUE TITLE
Feature Request: do not use local storage (or cookies) to store data

### ISSUE THREAD

**Issue by ls-2020** [Owyn/Universal_Dark_Theme#6]
I really like this script, but please do not use local storage (or cookies) to store data. I frequently delete local storage and cookies with "clear all browsing data"-Extension to remove all trackers. This resets universal dark theme settings and i really do not want to disable local storage or cookie clearing just for a userscript. So this userscript is not as useful for me as it could be, because i can use it only temporary.
I do not know if it is possible to store configuration data elsewhere, but if it is possible please do so!
If it is not possible please add a var that users can edit and add sites. Like UDT_SITES="site1.com, site2.org, ..." 
I Know this var would be overwritten after an update of the script, but this solution would still be way better than always loosing the config after cleaning trackers. Thanks!

**Comment by Owyn** [comment]
LocalStorage is exactly the place designed to store settings of apps such as this, it is not cross-site and only used for that exact site by that exact site,
and you are willingly clearing it yourself

But of course if you are a spy or political journalist at the risk - you should avoid leaving anything behind including script settings anywhere, even using script managers put you at risk, just stick to the default settings of the TOR browser and you'll be safe 👍🏻

**Comment by ls-2020** [comment]
sad to hear that it seams you don't understand how local storage is abused by many websites as persistent cookies and referring to tor is nonsense and off-topic. probably you should take a look in your local storage folder and see how much stuff is stored there without your consent. i just can recommend everybody to clear it as often as possible. so i will either edit your script for my personal use or just use stylus instead, so feel free to close this and have a nice day.

**Comment by Owyn** [comment]
By clearing site data - you are just breaking everything on those sites, that's the expected result

If cookies are set - it is already too late, same as with viruses lol, so instead of clearing and breaking stuff - consider not letting unwanted things in, e.g. with:
- uBlock
- NoScript
- dns filtering (nextdns or adguard dns)

Some peace of mind is better than constantly worrying and trying to extinguish the fire
